declare type Print = (...value: Array<string | TemplateStringsArray>) => void;
declare type Printer = Print & {
    error: Printer;
    warn: Printer;
    bold: Printer;
    dim: Printer;
    italic: Printer;
    underline: Printer;
    blink: Printer;
    fastblink: Printer;
    reverse: Printer;
    hidden: Printer;
    default: Printer;
    black: Printer;
    red: Printer;
    green: Printer;
    yellow: Printer;
    blue: Printer;
    magenta: Printer;
    white: Printer;
    cyan: Printer;
    bgBlack: Printer;
    bgRed: Printer;
    bgGreen: Printer;
    bgYellow: Printer;
    bgBlue: Printer;
    bgMagenta: Printer;
    bgWhite: Printer;
    bgCyan: Printer;
    brightBlack: Printer;
    brightRed: Printer;
    brightGreen: Printer;
    brightYellow: Printer;
    brightBlue: Printer;
    brightMagenta: Printer;
    brightWhite: Printer;
    brightCyan: Printer;
    bgBrightBlack: Printer;
    bgBrightRed: Printer;
    bgBrightGreen: Printer;
    bgBrightYellow: Printer;
    bgBrightBlue: Printer;
    bgBrightMagenta: Printer;
    bgBrightWhite: Printer;
    bgBrightCyan: Printer;
};
/** Export printers **/
export declare const print: Printer;
export default print;
